# Generated by Django 5.1.1 on 2024-09-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
