# Generated by Django 5.1.1 on 2024-09-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0002_alter_fruits_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristicas', models.JSONField(blank=True, default=dict, help_text='Características do produto em formato JSON.')),
            ],
        ),
    ]
