# Generated by Django 5.1.1 on 2024-09-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='report',
            name='fruits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
