# Generated by Django 5.1.1 on 2024-09-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0004_remove_report_caracteristicas_report_fruits_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
