# Generated by Django 5.1.1 on 2024-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0005_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.CharField(max_length=100)),
                ('fruit', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
