# Generated by Django 5.1.1 on 2024-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0007_rename_users_reports_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
