# Generated by Django 5.1.1 on 2024-09-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0008_alter_reports_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
