# Generated by Django 5.1.1 on 2024-09-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_stand_app', '0009_alter_reports_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruits',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='value',
            field=models.FloatField(),
        ),
    ]
